# Generated by Django 6.0.7 on 2026-07-29 02:33

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('optimized_image', models.ImageField(blank=True, null=True, upload_to='scores/optimized/')),
                ('ocr_raw_text', models.TextField(blank=True, default='')),
                ('chords', models.JSONField(blank=True, default=list)),
                ('original_key', models.CharField(blank=True, default='', max_length=10)),
                ('transpose_semitones', models.IntegerField(default=0)),
                ('lyrics_or_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
