# Generated by Django 6.0.7 on 2026-07-29 23:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_scoresheet_result_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=200)),
                ('original_image', models.ImageField(blank=True, null=True, upload_to='songs/original/')),
                ('chords', models.JSONField(blank=True, default=list)),
                ('ocr_raw_text', models.TextField(blank=True, default='')),
                ('original_key', models.CharField(blank=True, default='', max_length=10)),
                ('share_token', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('corrected', '수정본'), ('transposed', '변조본')], default='corrected', max_length=20)),
                ('transpose_semitones', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='songs/variants/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='scores.song')),
            ],
            options={
                'ordering': ['transpose_semitones', '-created_at'],
            },
        ),
    ]
