# Generated by Django 6.0.7 on 2026-08-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_remove_scoresheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorevariant',
            name='chord_font_size',
            field=models.IntegerField(default=13),
        ),
        migrations.AddField(
            model_name='song',
            name='chord_font_size',
            field=models.IntegerField(default=13),
        ),
    ]
